# -*- coding: utf-8 -*-
"""Tic Tac To Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jeziU3dzh4ZTu1mC5kvEihVfwcjm6-NN
"""

def display_board(board):
    print("\n\n")
    print(" " + board[7] + " | " + board[8] + " | " + board[9])
    print("-----------")
    print(" " + board[4] + " | " + board[5] + " | " + board[6])
    print("-----------")
    print(" " + board[1] + " | " + board[2] + " | " + board[3])

def player_input():
    marker = ''
    while not (marker == 'X' or marker == 'O'):
        marker = input('Player 1: Do you want to be X or O? ').upper()

    if marker == 'X':
        return ('X', 'O')
    else:
        return ('O', 'X')

def place_marker(board, marker, position):
    board[position] = marker

def win_check(board, mark):
    return ((board[7] == mark and board[8] == mark and board[9] == mark) or # across the top
            (board[4] == mark and board[5] == mark and board[6] == mark) or # across the middle
            (board[1] == mark and board[2] == mark and board[3] == mark) or # across the bottom
            (board[7] == mark and board[4] == mark and board[1] == mark) or # down the left side
            (board[8] == mark and board[5] == mark and board[2] == mark) or # down the middle
            (board[9] == mark and board[6] == mark and board[3] == mark) or # down the right side
            (board[7] == mark and board[5] == mark and board[3] == mark) or # diagonal
            (board[9] == mark and board[5] == mark and board[1] == mark)) # diagonal

import random

def choose_first():
    if random.randint(0, 1) == 0:
        return 'Player 2'
    else:
        return 'Player 1'

def space_check(board, position):
    return board[position] == ' '

def full_board_check(board):
    for i in range(1, 10):
        if space_check(board, i):
            return False
    return True

def player_choice(board):
    position = 0
    while position not in [1, 2, 3, 4, 5, 6, 7, 8, 9] or not space_check(board, position):
        try:
            position = int(input('Choose your next position: (1-9) '))
        except ValueError:
            print("Invalid input. Please enter a number between 1 and 9.")
    return position

def computer_choice(board, player_marker, opponent_marker):
    possible_moves = []
    for i in range(1, 10):
        if space_check(board, i):
            possible_moves.append(i)

    # Check for winning move for computer
    for move in possible_moves:
        board_copy = list(board)
        board_copy[move] = opponent_marker
        if win_check(board_copy, opponent_marker):
            return move

    # Check for winning move for player to block
    for move in possible_moves:
        board_copy = list(board)
        board_copy[move] = player_marker
        if win_check(board_copy, player_marker):
            return move

    # Try to take corners
    corners = [1, 3, 7, 9]
    available_corners = [move for move in possible_moves if move in corners]
    if available_corners:
        return random.choice(available_corners)

    # Try to take the center
    if 5 in possible_moves:
        return 5

    # Take any available side
    sides = [2, 4, 6, 8]
    available_sides = [move for move in possible_moves if move in sides]
    if available_sides:
        return random.choice(available_sides)

    return random.choice(possible_moves) # Fallback to any random move

def replay():
    return input('Do you want to play again? Enter Yes or No: ').lower().startswith('y')

print('Welcome to Tic Tac Toe!')

while True:
    theBoard = [' '] * 10
    player1_marker, player2_marker = player_input()

    game_mode = ''
    while game_mode not in ['H', 'C']:
        game_mode = input('Do you want to play against another Human (H) or Computer (C)? ').upper()

    turn = choose_first()
    print(turn + ' will go first.')

    game_on = True

    while game_on:
        if turn == 'Player 1':
            display_board(theBoard)
            position = player_choice(theBoard)
            place_marker(theBoard, player1_marker, position)

            if win_check(theBoard, player1_marker):
                display_board(theBoard)
                print('Congratulations! Player 1 has won the game!')
                game_on = False
            else:
                if full_board_check(theBoard):
                    display_board(theBoard)
                    print('The game is a draw!')
                    game_on = False
                else:
                    turn = 'Player 2'

        else: # Player 2's turn
            if game_mode == 'H': # Human Player 2
                display_board(theBoard)
                position = player_choice(theBoard)
            else: # Computer Player
                print("Computer's Turn...")
                position = computer_choice(theBoard, player1_marker, player2_marker)

            place_marker(theBoard, player2_marker, position)

            if win_check(theBoard, player2_marker):
                display_board(theBoard)
                print('Congratulations! ' + ('Player 2' if game_mode == 'H' else 'Computer') + ' has won the game!')
                game_on = False
            else:
                if full_board_check(theBoard):
                    display_board(theBoard)
                    print('The game is a draw!')
                    game_on = False
                else:
                    turn = 'Player 1'

    if not replay():
        break

"""## Interactive Tic-Tac-Toe with `ipywidgets`

This version of the game uses `ipywidgets` to create a clickable board directly in your Colab output. You can choose your marker (X or O) and your opponent (Human or Computer).

Run the following cells to start playing!
"""

from IPython.display import HTML

# Inject custom CSS for glowing effects
display(HTML('''
<style>
.widget-button.winning-glow {
    animation: win-glow 1s infinite alternate;
}
@keyframes win-glow {
    from { box-shadow: 0 0 5px #fff, 0 0 10px #fff, 0 0 15px #28a745, 0 0 20px #28a745, 0 0 25px #28a745; } /* Green glow for win */
    to { box-shadow: 0 0 10px #fff, 0 0 20px #fff, 0 0 30px #28a745, 0 0 40px #28a745, 0 0 50px #28a745; }
}
.widget-button.draw-glow {
    animation: draw-glow 1s infinite alternate;
}
@keyframes draw-glow {
    from { box-shadow: 0 0 5px #fff, 0 0 10px #fff, 0 0 15px #17a2b8, 0 0 20px #17a2b8; } /* Teal glow for draw */
    to { box-shadow: 0 0 10px #fff, 0 0 20px #fff, 0 0 30px #17a2b8, 0 0 40px #17a2b8; }
}
</style>
'''))

import ipywidgets as widgets
from IPython.display import display, clear_output, HTML
import random

# --- Global Game State --- #
board = [' '] * 10  # Board represented as a list, index 0 is ignored
player_marker = 'X'
computer_marker = 'O'
opponent_type = 'Computer' # Can be 'Computer' or 'Human'
current_turn = 'Player 1'
game_active = False

# --- Game Logic Functions (Adapted from previous version) --- #
def win_check(board_state, mark):
    winning_combinations = [
        [7, 8, 9], [4, 5, 6], [1, 2, 3], # rows
        [7, 4, 1], [8, 5, 2], [9, 6, 3], # columns
        [7, 5, 3], [9, 5, 1]             # diagonals
    ]
    for combo in winning_combinations:
        if (board_state[combo[0]] == mark and
            board_state[combo[1]] == mark and
            board_state[combo[2]] == mark):
            return combo # Return the winning combination
    return None # No win

def space_check(board_state, position):
    return board_state[position] == ' '

def full_board_check(board_state):
    for i in range(1, 10):
        if space_check(board_state, i):
            return False
    return True

def computer_choice(board_state, p_marker, c_marker):
    possible_moves = []
    for i in range(1, 10):
        if space_check(board_state, i):
            possible_moves.append(i)

    # Check for winning move for computer
    for move in possible_moves:
        board_copy = list(board_state)
        board_copy[move] = c_marker
        if win_check(board_copy, c_marker):
            return move

    # Check for winning move for player to block
    for move in possible_moves:
        board_copy = list(board_state)
        board_copy[move] = p_marker
        if win_check(board_copy, p_marker):
            return move

    # Try to take corners
    corners = [1, 3, 7, 9]
    available_corners = [move for move in possible_moves if move in corners]
    if available_corners:
        return random.choice(available_corners)

    # Try to take the center
    if 5 in possible_moves:
        return 5

    # Take any available side
    sides = [2, 4, 6, 8]
    available_sides = [move for move in possible_moves if move in sides]
    if available_sides:
        return random.choice(available_sides)

    if possible_moves:
        return random.choice(possible_moves) # Fallback to any random move
    return None # Should not happen in a non-full board

def update_board_display():
    for i in range(1, 10):
        marker = board[i]
        button_widget = game_buttons[i-1]
        button_widget.description = marker

        # Clear custom glowing classes by filtering the _dom_classes tuple
        current_classes = list(button_widget._dom_classes)
        button_widget._dom_classes = tuple(c for c in current_classes if c not in ['winning-glow', 'draw-glow'])
        button_widget.button_style = '' # Reset button style as well

        if marker == 'X':
            button_widget.button_style = 'primary'
            button_widget.disabled = True
        elif marker == 'O':
            button_widget.button_style = 'warning'
            button_widget.disabled = True
        else:
            button_widget.disabled = False

def reset_game():
    global board, current_turn, game_active
    board = [' '] * 10
    current_turn = random.choice(['Player 1', 'Player 2'])
    game_active = True
    update_board_display() # This will set all buttons to ' ', '' style, and enabled
    with game_output:
        clear_output(wait=True)
        # Removed: print(f"New game started! {current_turn} goes first.")
        if current_turn == 'Player 2' and opponent_type == 'Computer':
            computer_make_move()

# --- UI Elements --- #
game_output = widgets.Output()

game_buttons = []
for i in range(9):
    button = widgets.Button(description=' ', layout=widgets.Layout(width='80px', height='80px', font_size='36px')) # Increased size
    game_buttons.append(button)

def computer_make_move():
    global board, current_turn, game_active
    if not game_active: return

    if not full_board_check(board):
        comp_pos = computer_choice(board, player_marker, computer_marker)
        if comp_pos is not None:
            board[comp_pos] = computer_marker
            update_board_display()
            winning_combo = win_check(board, computer_marker)
            if winning_combo:
                for pos in winning_combo:
                    current_classes = list(game_buttons[pos-1]._dom_classes)
                    if 'winning-glow' not in current_classes:
                        current_classes.append('winning-glow')
                    game_buttons[pos-1]._dom_classes = tuple(current_classes)
                with game_output:
                    print(f"Game Over! {'Computer'} wins!")
                game_active = False
                for b in game_buttons: b.disabled = True
                return
            elif full_board_check(board):
                for b in game_buttons:
                    current_classes = list(b._dom_classes)
                    if 'draw-glow' not in current_classes:
                        current_classes.append('draw-glow')
                    b._dom_classes = tuple(current_classes)
                with game_output:
                    print("Game Over! It's a draw!")
                game_active = False
                for b in game_buttons: b.disabled = True
                return
            current_turn = 'Player 1'
            # Removed: print(f"It's {current_turn}'s turn.")

def on_square_click(button):
    global board, current_turn, game_active, player_marker, computer_marker
    if not game_active or current_turn != 'Player 1':
        return

    clicked_pos = game_buttons.index(button) + 1

    if space_check(board, clicked_pos):
        board[clicked_pos] = player_marker
        update_board_display()

        winning_combo = win_check(board, player_marker)
        if winning_combo:
            for pos in winning_combo:
                current_classes = list(game_buttons[pos-1]._dom_classes)
                if 'winning-glow' not in current_classes:
                    current_classes.append('winning-glow')
                game_buttons[pos-1]._dom_classes = tuple(current_classes)
            with game_output:
                print("Game Over! Player 1 wins!")
            game_active = False
            for b in game_buttons: b.disabled = True
            return
        elif full_board_check(board):
            for b in game_buttons:
                current_classes = list(b._dom_classes)
                if 'draw-glow' not in current_classes:
                    current_classes.append('draw-glow')
                b._dom_classes = tuple(current_classes)
            with game_output:
                print("Game Over! It's a draw!")
            game_active = False
            for b in game_buttons: b.disabled = True
            return

        current_turn = 'Player 2'
        # Removed: print(f"It's {current_turn}'s turn.")

        if opponent_type == 'Computer':
            computer_make_move()
        elif opponent_type == 'Human':
             # For human vs human, just switch turns, no auto move
             pass # Logic will be handled by the next human click


for button in game_buttons:
    button.on_click(on_square_click)

# --- Control Buttons --- #
marker_choice_label = widgets.Label("Choose your marker:")
x_button = widgets.Button(description='X', button_style='info', layout=widgets.Layout(width='60px')) # 'info' for initially selected
o_button = widgets.Button(description='O', button_style='', layout=widgets.Layout(width='60px'))

def on_marker_choice(button):
    global player_marker, computer_marker
    if button.description == 'X':
        player_marker = 'X'
        computer_marker = 'O'
        x_button.button_style = 'info'
        o_button.button_style = ''
    else:
        player_marker = 'O'
        computer_marker = 'X'
        o_button.button_style = 'info'
        x_button.button_style = ''
    with game_output:
        clear_output(wait=True)
        print(f"Player 1 chose {player_marker}. Computer will be {computer_marker}.")
    reset_game() # Reset game to apply new marker choices

x_button.on_click(on_marker_choice)
o_button.on_click(on_marker_choice)

opponent_choice_label = widgets.Label("Choose opponent:")
human_opponent_button = widgets.Button(description='Human', layout=widgets.Layout(width='auto'))
computer_opponent_button = widgets.Button(description='Computer', button_style='info', layout=widgets.Layout(width='auto'))

def on_opponent_choice(button):
    global opponent_type
    if button.description == 'Human':
        opponent_type = 'Human'
        human_opponent_button.button_style = 'info'
        computer_opponent_button.button_style = ''
        with game_output:
            print("Playing against another Human.")
    else:
        opponent_type = 'Computer'
        computer_opponent_button.button_style = 'info'
        human_opponent_button.button_style = ''
        with game_output:
            print("Playing against the Computer.")
    reset_game() # Reset game to apply new opponent choice

human_opponent_button.on_click(on_opponent_choice)
computer_opponent_button.on_click(on_opponent_choice)

new_game_button = widgets.Button(description='New Game', button_style='success', layout=widgets.Layout(width='auto'))
new_game_button.on_click(lambda b: reset_game())

# --- Layout --- #
board_grid = widgets.GridBox(game_buttons,
                             layout=widgets.Layout(
                                 width='250px', # Adjusted width for larger buttons (3*80 + 2*5 gap)
                                 grid_template_columns='repeat(3, 80px)', # Adjusted for larger buttons
                                 grid_template_rows='repeat(3, 80px)',    # Adjusted for larger buttons
                                 gap='5px',
                                 padding='10px',
                                 border='2px solid lightgray'
                             ))

marker_selector = widgets.HBox([marker_choice_label, x_button, o_button])
opponent_selector = widgets.HBox([opponent_choice_label, human_opponent_button, computer_opponent_button])

controls_box = widgets.VBox([marker_selector, opponent_selector, new_game_button], layout=widgets.Layout(align_items='center', margin='10px 0'))

game_ui = widgets.VBox([game_output, board_grid, controls_box], layout=widgets.Layout(align_items='center'))

display(game_ui)

# Initialize a new game when the cell is run
reset_game()